#!/usr/bin/env node
/**
 * Comprehensive smoke test for FaisabilitéBiomasse application
 * Tests all major features to ensure zero bugs
 */

const http = require('http');

const BASE_URL = 'http://localhost:3002';
let testResults = [];
let projectId = null;

// Helper function to make HTTP requests
function makeRequest(method, path, data = null) {
  return new Promise((resolve, reject) => {
    const url = new URL(path, BASE_URL);
    const options = {
      hostname: url.hostname,
      port: url.port,
      path: url.pathname + url.search,
      method: method,
      headers: {
        'Content-Type': 'application/json',
      }
    };

    const req = http.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          resolve({
            status: res.statusCode,
            headers: res.headers,
            body: body ? JSON.parse(body) : null,
            rawBody: body
          });
        } catch (e) {
          resolve({
            status: res.statusCode,
            headers: res.headers,
            body: null,
            rawBody: body
          });
        }
      });
    });

    req.on('error', reject);
    if (data) req.write(JSON.stringify(data));
    req.end();
  });
}

// Test function
function test(name, condition, details = '') {
  const result = condition ? '✓ PASS' : '✗ FAIL';
  testResults.push({ name, passed: condition, details });
  console.log(`${result}: ${name}${details ? ' (' + details + ')' : ''}`);
}

// Main test suite
async function runTests() {
  console.log('\n========== FAISABILITÉ BIOMASSE - SMOKE TEST ==========\n');

  try {
    // Test 1: Welcome page
    console.log('>>> Testing Welcome Page...');
    const welcomePage = await makeRequest('GET', '/');
    test('Welcome page loads', welcomePage.status === 200, `HTTP ${welcomePage.status}`);

    // Test 2: Dashboard page
    console.log('\n>>> Testing Dashboard...');
    const dashboardPage = await makeRequest('GET', '/dashboard');
    test('Dashboard page loads', dashboardPage.status === 200, `HTTP ${dashboardPage.status}`);

    // Test 3: GET all projects (empty list)
    console.log('\n>>> Testing Affaires API...');
    const affairesEmpty = await makeRequest('GET', '/api/affaires');
    test('GET /api/affaires returns 200', affairesEmpty.status === 200, `HTTP ${affairesEmpty.status}`);
    test('Empty projects list is array', Array.isArray(affairesEmpty.body), `Type: ${typeof affairesEmpty.body}`);

    // Test 4: Create a project
    console.log('\n>>> Testing Project Creation...');
    const newProject = {
      referenceAffaire: 'SMOKE-TEST-001',
      nomClient: 'Smoke Test Client',
      adresse: '123 Rue de Test',
      ville: 'Paris',
      departement: '75',
      latitude: 48.8566,
      longitude: 2.3522,
      notes: 'Smoke test project'
    };
    const createResponse = await makeRequest('POST', '/api/affaires', newProject);
    test('Create project returns 201', createResponse.status === 201, `HTTP ${createResponse.status}`);
    test('Created project has ID', createResponse.body && createResponse.body.id, `ID: ${createResponse.body?.id?.substring(0, 10)}...`);
    
    if (createResponse.body && createResponse.body.id) {
      projectId = createResponse.body.id;
      // Reference is auto-generated by the server, not the one we sent
      test('Project reference auto-generated', createResponse.body.referenceAffaire && createResponse.body.referenceAffaire !== 'SMOKE-TEST-001');
      test('Project has correct client', createResponse.body.nomClient === 'Smoke Test Client');
    }

    // Test 5: GET created project
    const initialProjectCount = affairesEmpty.body.length;
    if (projectId) {
      console.log('\n>>> Testing Get Project...');
      const getProject = await makeRequest('GET', `/api/affaires/${projectId}`);
      test('GET single project returns 200', getProject.status === 200, `HTTP ${getProject.status}`);
      test('Retrieved project has correct ID', getProject.body?.id === projectId);
    } else {
      test('Skip: Could not get project ID', false, 'Project creation failed');
    }

    // Test 6: Get all projects
    console.log('\n>>> Testing List Projects...');
    const affairesWithData = await makeRequest('GET', '/api/affaires');
    test('GET /api/affaires returns 200', affairesWithData.status === 200, `HTTP ${affairesWithData.status}`);
    test('New project appears in list', affairesWithData.body.length > initialProjectCount, `Count: ${affairesWithData.body.length}`);

    // Test 7: GET costs database
    console.log('\n>>> Testing Costs Database...');
    const costs = await makeRequest('GET', '/api/costs');
    test('GET /api/costs returns 200', costs.status === 200, `HTTP ${costs.status}`);
    test('Costs is array', Array.isArray(costs.body), `Type: ${typeof costs.body}`);
    test('Has cost items', costs.body.length > 0, `Count: ${costs.body.length}`);
    
    if (costs.body.length > 0) {
      test('Cost items have required fields', 
        costs.body[0].id && costs.body[0].designation && costs.body[0].prixUnitaire !== undefined,
        `Fields: id, designation, prixUnitaire`);
    }

    // Test 8: Admin costs page
    console.log('\n>>> Testing Admin Pages...');
    const adminCosts = await makeRequest('GET', '/admin/costs');
    test('Admin costs page loads', adminCosts.status === 200, `HTTP ${adminCosts.status}`);

    // Test 9: Error cases
    console.log('\n>>> Testing Error Handling...');
    const notFound = await makeRequest('GET', '/api/affaires/invalid-id-xyz');
    test('GET non-existent project returns 404', notFound.status === 404, `HTTP ${notFound.status}`);

    const badRequest = await makeRequest('POST', '/api/affaires', { invalid: 'data' });
    test('Invalid project creation returns error', badRequest.status !== 200 || badRequest.body.error, 'Error handled');

  } catch (error) {
    console.error('Error during tests:', error.message);
    test('Exception thrown', false, error.message);
  }

  // Summary
  console.log('\n========== TEST SUMMARY ==========\n');
  const passed = testResults.filter(r => r.passed).length;
  const total = testResults.length;
  const passRate = ((passed / total) * 100).toFixed(1);
  
  console.log(`Passed: ${passed}/${total} (${passRate}%)`);
  
  if (passed === total) {
    console.log('\n✓ ALL TESTS PASSED! Application is ZERO BUG READY!\n');
  } else {
    console.log('\n✗ Some tests failed. Details:');
    testResults.filter(r => !r.passed).forEach(r => {
      console.log(`  - ${r.name}${r.details ? ': ' + r.details : ''}`);
    });
    console.log();
  }

  process.exit(passed === total ? 0 : 1);
}

// Run tests
runTests().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
