import { NextResponse } from 'next/server';
import { db, isAdmin } from '@/lib/db';

// Valeurs officielles SDES/Météo France 1996-2022, extraites de l'Excel
// faisabilite_biomasse_version_2.xlsm, feuille Meteo (col. Moyenne + Text Base)
const DJU_EXCEL = [
  { departement: 'Ain', code: '01', djuMoyenne: 2148.1, tempExtBase: -10 },
  { departement: 'Aisne', code: '02', djuMoyenne: 2266.5, tempExtBase: -7 },
  { departement: 'Allier', code: '03', djuMoyenne: 2127.9, tempExtBase: -8 },
  { departement: 'Alpes-de-Haute-Provence', code: '04', djuMoyenne: 1833.2, tempExtBase: -8 },
  { departement: 'Hautes-Alpes', code: '05', djuMoyenne: 2342.9, tempExtBase: -10 },
  { departement: 'Alpes-Maritimes', code: '06', djuMoyenne: 1017.4, tempExtBase: -2 },
  { departement: 'Ardèche', code: '07', djuMoyenne: 1738.1, tempExtBase: -7 },
  { departement: 'Ardennes', code: '08', djuMoyenne: 2472.2, tempExtBase: -10 },
  { departement: 'Ariège', code: '09', djuMoyenne: 1843.1, tempExtBase: -5 },
  { departement: 'Aube', code: '10', djuMoyenne: 2261.0, tempExtBase: -8 },
  { departement: 'Aude', code: '11', djuMoyenne: 1396.0, tempExtBase: -5 },
  { departement: 'Aveyron', code: '12', djuMoyenne: 2069.5, tempExtBase: -7 },
  { departement: 'Bouches-du-Rhône', code: '13', djuMoyenne: 1075.0, tempExtBase: -3 },
  { departement: 'Calvados', code: '14', djuMoyenne: 2187.1, tempExtBase: -5 },
  { departement: 'Cantal', code: '15', djuMoyenne: 2609.5, tempExtBase: -10 },
  { departement: 'Charente', code: '16', djuMoyenne: 1777.9, tempExtBase: -5 },
  { departement: 'Charente-Maritime', code: '17', djuMoyenne: 1667.4, tempExtBase: -4 },
  { departement: 'Cher', code: '18', djuMoyenne: 2004.1, tempExtBase: -7 },
  { departement: 'Corrèze', code: '19', djuMoyenne: 2040.2, tempExtBase: -7 },
  { departement: "Corse-du-Sud", code: '2A', djuMoyenne: 839.6, tempExtBase: -1 },
  { departement: 'Haute-Corse', code: '2B', djuMoyenne: 1153.0, tempExtBase: -3 },
  { departement: "Côte-d'Or", code: '21', djuMoyenne: 2262.9, tempExtBase: -10 },
  { departement: "Côtes-d'Armor", code: '22', djuMoyenne: 1918.4, tempExtBase: -4 },
  { departement: 'Creuse', code: '23', djuMoyenne: 2291.5, tempExtBase: -8 },
  { departement: 'Dordogne', code: '24', djuMoyenne: 1743.7, tempExtBase: -5 },
  { departement: 'Doubs', code: '25', djuMoyenne: 2693.7, tempExtBase: -13 },
  { departement: 'Drôme', code: '26', djuMoyenne: 1719.6, tempExtBase: -7 },
  { departement: 'Eure', code: '27', djuMoyenne: 2165.3, tempExtBase: -6 },
  { departement: 'Eure-et-Loir', code: '28', djuMoyenne: 2111.6, tempExtBase: -7 },
  { departement: 'Finistère', code: '29', djuMoyenne: 1871.0, tempExtBase: -3 },
  { departement: 'Gard', code: '30', djuMoyenne: 1298.7, tempExtBase: -4 },
  { departement: 'Haute-Garonne', code: '31', djuMoyenne: 1555.5, tempExtBase: -6 },
  { departement: 'Gers', code: '32', djuMoyenne: 1605.0, tempExtBase: -6 },
  { departement: 'Gironde', code: '33', djuMoyenne: 1618.1, tempExtBase: -4 },
  { departement: 'Hérault', code: '34', djuMoyenne: 1199.0, tempExtBase: -3 },
  { departement: 'Ille-et-Vilaine', code: '35', djuMoyenne: 2008.3, tempExtBase: -5 },
  { departement: 'Indre', code: '36', djuMoyenne: 1993.2, tempExtBase: -7 },
  { departement: 'Indre-et-Loire', code: '37', djuMoyenne: 1914.4, tempExtBase: -6 },
  { departement: 'Isère', code: '38', djuMoyenne: 2083.3, tempExtBase: -10 },
  { departement: 'Jura', code: '39', djuMoyenne: 2619.2, tempExtBase: -13 },
  { departement: 'Landes', code: '40', djuMoyenne: 1643.5, tempExtBase: -4 },
  { departement: 'Loir-et-Cher', code: '41', djuMoyenne: 2014.1, tempExtBase: -7 },
  { departement: 'Loire', code: '42', djuMoyenne: 2118.3, tempExtBase: -9 },
  { departement: 'Haute-Loire', code: '43', djuMoyenne: 2548.1, tempExtBase: -10 },
  { departement: 'Loire-Atlantique', code: '44', djuMoyenne: 1868.8, tempExtBase: -5 },
  { departement: 'Loiret', code: '45', djuMoyenne: 2062.5, tempExtBase: -7 },
  { departement: 'Lot', code: '46', djuMoyenne: 1840.9, tempExtBase: -6 },
  { departement: 'Lot-et-Garonne', code: '47', djuMoyenne: 1678.5, tempExtBase: -5 },
  { departement: 'Lozère', code: '48', djuMoyenne: 2513.4, tempExtBase: -10 },
  { departement: 'Maine-et-Loire', code: '49', djuMoyenne: 1917.1, tempExtBase: -6 },
  { departement: 'Manche', code: '50', djuMoyenne: 2078.7, tempExtBase: -4 },
  { departement: 'Marne', code: '51', djuMoyenne: 2282.0, tempExtBase: -9 },
  { departement: 'Haute-Marne', code: '52', djuMoyenne: 2499.4, tempExtBase: -11 },
  { departement: 'Mayenne', code: '53', djuMoyenne: 2113.7, tempExtBase: -6 },
  { departement: 'Meurthe-et-Moselle', code: '54', djuMoyenne: 2548.4, tempExtBase: -12 },
  { departement: 'Meuse', code: '55', djuMoyenne: 2543.9, tempExtBase: -12 },
  { departement: 'Morbihan', code: '56', djuMoyenne: 1801.7, tempExtBase: -3 },
  { departement: 'Moselle', code: '57', djuMoyenne: 2537.8, tempExtBase: -12 },
  { departement: 'Nièvre', code: '58', djuMoyenne: 2162.4, tempExtBase: -10 },
  { departement: 'Nord', code: '59', djuMoyenne: 2144.3, tempExtBase: -9 },
  { departement: 'Oise', code: '60', djuMoyenne: 2223.5, tempExtBase: -7 },
  { departement: 'Orne', code: '61', djuMoyenne: 2107.7, tempExtBase: -7 },
  { departement: 'Pas-de-Calais', code: '62', djuMoyenne: 2222.4, tempExtBase: -8 },
  { departement: 'Puy-de-Dôme', code: '63', djuMoyenne: 2121.2, tempExtBase: -9 },
  { departement: 'Pyrénées-Atlantiques', code: '64', djuMoyenne: 1709.1, tempExtBase: -5 },
  { departement: 'Hautes-Pyrénées', code: '65', djuMoyenne: 1858.0, tempExtBase: -7 },
  { departement: 'Pyrénées-Orientales', code: '66', djuMoyenne: 1088.8, tempExtBase: -4 },
  { departement: 'Bas-Rhin', code: '67', djuMoyenne: 2559.0, tempExtBase: -13 },
  { departement: 'Haut-Rhin', code: '68', djuMoyenne: 2409.5, tempExtBase: -13 },
  { departement: 'Rhône', code: '69', djuMoyenne: 1928.3, tempExtBase: -8 },
  { departement: 'Haute-Saône', code: '70', djuMoyenne: 2499.7, tempExtBase: -12 },
  { departement: 'Saône-et-Loire', code: '71', djuMoyenne: 2193.5, tempExtBase: -10 },
  { departement: 'Sarthe', code: '72', djuMoyenne: 2045.8, tempExtBase: -6 },
  { departement: 'Savoie', code: '73', djuMoyenne: 2499.1, tempExtBase: -12 },
  { departement: 'Haute-Savoie', code: '74', djuMoyenne: 2403.5, tempExtBase: -12 },
  { departement: 'Paris', code: '75', djuMoyenne: 1975.8, tempExtBase: -7 },
  { departement: 'Seine-Maritime', code: '76', djuMoyenne: 2224.1, tempExtBase: -6 },
  { departement: 'Seine-et-Marne', code: '77', djuMoyenne: 2115.1, tempExtBase: -8 },
  { departement: 'Yvelines', code: '78', djuMoyenne: 2064.2, tempExtBase: -7 },
  { departement: 'Deux-Sèvres', code: '79', djuMoyenne: 1851.6, tempExtBase: -6 },
  { departement: 'Somme', code: '80', djuMoyenne: 2289.4, tempExtBase: -8 },
  { departement: 'Tarn', code: '81', djuMoyenne: 1683.5, tempExtBase: -6 },
  { departement: 'Tarn-et-Garonne', code: '82', djuMoyenne: 1639.9, tempExtBase: -5 },
  { departement: 'Var', code: '83', djuMoyenne: 873.7, tempExtBase: -1 },
  { departement: 'Vaucluse', code: '84', djuMoyenne: 1354.9, tempExtBase: -5 },
  { departement: 'Vendée', code: '85', djuMoyenne: 1790.6, tempExtBase: -4 },
  { departement: 'Vienne', code: '86', djuMoyenne: 1905.9, tempExtBase: -6 },
  { departement: 'Haute-Vienne', code: '87', djuMoyenne: 2028.0, tempExtBase: -6 },
  { departement: 'Vosges', code: '88', djuMoyenne: 2709.4, tempExtBase: -14 },
  { departement: 'Yonne', code: '89', djuMoyenne: 2163.1, tempExtBase: -9 },
  { departement: 'Territoire de Belfort', code: '90', djuMoyenne: 2544.5, tempExtBase: -13 },
  { departement: 'Essonne', code: '91', djuMoyenne: 2076.1, tempExtBase: -7 },
  { departement: 'Hauts-de-Seine', code: '92', djuMoyenne: 1966.1, tempExtBase: -7 },
  { departement: 'Seine-Saint-Denis', code: '93', djuMoyenne: 2014.8, tempExtBase: -7 },
  { departement: 'Val-de-Marne', code: '94', djuMoyenne: 2000.2, tempExtBase: -7 },
  { departement: "Val-d'Oise", code: '95', djuMoyenne: 2005.1, tempExtBase: -7 },
];

export async function POST() {
  if (!(await isAdmin())) {
    return NextResponse.json({ error: 'Accès réservé aux administrateurs' }, { status: 403 });
  }

  let updated = 0;
  for (const m of DJU_EXCEL) {
    await db.meteoMoyenne.upsert({
      where: { departement: m.departement },
      update: { code: m.code, djuMoyenne: m.djuMoyenne, tempExtBase: m.tempExtBase },
      create: m,
    });
    updated++;
  }

  return NextResponse.json({ success: true, updated, message: `${updated} départements mis à jour avec les valeurs Excel officielles` });
}
